export const Products = [

 {
    id: 1,
    title: "waffel",
    images: "/img/reto1.jpg",
    price: 10,
    rating: 4.5,
    reviews: "900",
    },
 {
    id: 2,
    title:"Expresso coffee ",
    images:"/img/reito2.jpg",
    price: 12,
    rating: 4.5,
    reviews: "900",
    },
  {
    id: 3,
    title: "hot chocolate",
    images: "/img/reito3.jpg",
    price: 6,
    rating: 4,
    reviews: "900",
   },
    {
    id: 4,
    title: "Cornflakes",
    images: "/img/reito4.jpg",
    price: 16,
    rating: 4.5,
    reviews: "900",
   },
      {
    id: 5,
    title: "coffee",
    images: "/img/reito5.jpg",
    price: 7,
    rating: 3.5,
    reviews: "900",
   },
        {
    id: 6,
    title: "cookies",
    images: "/img/reito6.jpg",
    price: 20,
    rating: 5,
    reviews: "900",
   },
          {
    id: 7,
    title: "Ice mocha",
    images: "/img/reito8.jpg",
    price: 9,
    rating: 4.5,
    reviews: "900",
   },
            {
    id: 8,
    title: "cake",
    images: "/img/reito9.jpg",
    price: 13,
    rating: 4,
    reviews: "900",
   },
                     {
    id: 9,
    title: "doughnut",
    images: "/img/reito10.jpg",
    price: 20,
    rating: 5,
    reviews: "900",
   },


]